### ISSUE TITLE
not able to build nexus docker image

### ISSUE THREAD

**Issue by docfactory37** [digrouz/docker-nexus#1]
Hi,

Im trying to build your nexus build but it fails when i try and build.

Please see issue below.

`failure: repodata/repomd.xml from custom: [Errno 256] No more mirrors to try.
https://www.digrouz.com/repo/centos/7/x86_64/custom/repodata/repomd.xml: [Errno 14] curl#60 - "Issuer certificate is invalid."
[0mThe command '/bin/sh -c set -x &&     chmod 1777 /tmp &&     . /usr/local/bin/docker-entrypoint-functions.sh &&     MYUSER="${APPUSER}" &&     MYUID="${APPUID}" &&     MYGID="${APPGID}" &&     ConfigureUser &&     usermod -m -d ${SONATYPE_DIR} ${MYUSER} &&     yum-config-manager --add-repo /tmp/custom.repo &&     yum update -y &&     yum install -y       curl       tar       createrepo       java-1.8.0-openjdk-headless.x86_64       su-exec     &&     curl --fail --silent --location --retry 3 http://download.sonatype.com/nexus/3/nexus-${NEXUS_VERSION}-unix.tar.gz -o /tmp/nexus-${NEXUS_VERSION}-unix.tar.gz &&     mkdir -p ${SONATYPE_DIR} ${NEXUS_WORK} ${NEXUS_DATA} &&     tar xzf /tmp/nexus-${NEXUS_VERSION}-unix.tar.gz -C /tmp &&     mv /tmp/nexus-${NEXUS_VERSION} ${NEXUS_HOME} &&     ln -snf ${NEXUS_WORK} ${SONATYPE_WORK} &&     sed       -e '/^-Xms/d'       -e '/^-Xmx/d'       -e '/^-XX:MaxDirectMemorySize/d'     ${NEXUS_HOME}/bin/nexus.vmoptions &&     chown -R ${MYUSER}:${MYUSER} ${SONATYPE_DIR} ${NEXUS_HOME} ${SONATYPE_WORK} ${NEXUS_WORK} ${NEXUS_DATA} &&     yum clean all &&     mkdir /docker-entrypoint.d &&     chmod +x /usr/local/bin/docker-entrypoint.sh &&     ln -snf /usr/local/bin/docker-entrypoint.sh /docker-entrypoint.sh &&     rm -rf /tmp/*            /var/cache/yum/*            /var/tmp/*' returned a non-zero code: 1
Build step 'Docker Build and Publish' marked build as failure`

**Comment by docfactory37** [comment]
i have fixed the issue by updating the /root/tmp/custom.repo

**Comment by docfactory37** [comment]
can you please update custom.repo to the below

```
[custom]
name=custom
baseurl=https://repo.digrouz.com/repo/centos/$releasever/$basearch/custom
gpgcheck=0
enabled=1
```
i have tried but i dont have access to update it for you and create a PR for you to approve

**Comment by digrouz** [comment]
Should be fixed now, that's for spotting it!
